Print failure from EDPM service logs

diff --git a/ci/ci b/ci/ci
--- a/ci/ci
+++ b/ci/ci
@@ -174,7 +174,15 @@ _check_ctlplane() {
 }
 
 _check_dataplane() {
-    _assert_crs_of_a_kind_ready openstackdataplanedeployment
+    if ! _assert_crs_of_a_kind_ready openstackdataplanedeployment ; then
+        # get the failed service and prin the failure form the log
+        error=$(_assert_crs_of_a_kind_ready openstackdataplanedeployment | grep "execution.name") || true
+        [[ "$error" =~ ^.*execution.name[[:space:]]+(.+)[[:space:]]+execution.namespace.*$ ]]
+        service="${BASH_REMATCH[1]}"
+        grep "FAILED!" $K8S_RESOURCE_DIR/**/pods/"$service"*/logs/*.log | head -n2
+
+        return 1
+    fi
     _assert_crs_of_a_kind_ready openstackdataplanenodeset
 }
 
